name: rna-seq-analysis
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - samtools
  - bwa
  - python=3
  - hisat2
  - stringtie
  - r
  - bioconductor-biocinstaller
  - bioconductor-ballgown
  - r-tidyverse
  - r-devtools
  - r-dplyr
  - bioconductor-genefilter
  - pip
  - pip:
      - numpy
      - matplotlib
      - pandas
      - biopython
      - bioinfokit
